version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
